// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./components/Header/index.vue')['default']
    Indexe: typeof import('./components/Sidebar/indexe.vue')['default']
    Main: typeof import('./components/Main/index.vue')['default']
    Player: typeof import('./components/Player/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Header/search.vue')['default']
  }
}

export {}
